/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/boxtruckonly.glb -o src/views/home/comModels/BoxTruckOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import boxmodel from '../../../assets/models/animatedModels/boxtruckonly.glb';
export function BoxTruckOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(boxmodel)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.Pickup_2Action) {
      actions.Pickup_2Action.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Pickup_2" castShadow receiveShadow geometry={nodes.Pickup_2.geometry} material={materials['Mat.001']} position={[-1021.057, 0.446, 628.301]} rotation={[Math.PI / 2, 0, -0.319]} scale={6.923} />
      </group>
    </group>
  )
}

useGLTF.preload(boxmodel)
