/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/caronly.glb -o src/views/home/comModels/CarOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import car from '../../../assets/models/animatedModels/caronly.glb'
export function CarOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(car)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.car) {
      actions.car.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Car_3_2001" castShadow receiveShadow geometry={nodes.Car_3_2001.geometry} material={materials.Mat} position={[-787.987, -0.276, 215.328]} rotation={[Math.PI / 2, 0, -2.164]} scale={7.446} />
      </group>
    </group>
  )
}

useGLTF.preload(car)
