/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/droneboxonly.glb -o src/views/home/comModels/DroneBoxOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import drone from '../../../assets/models/animatedModels/droneboxonly.glb';
export function DroneBoxOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(drone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions.firstbox) {
      actions.firstbox.play();
    }
  }, [actions]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Box_3007" castShadow receiveShadow geometry={nodes.Box_3007.geometry} material={materials['Mat.001']} position={[-1026.121, 18.735, 489.487]} rotation={[Math.PI / 2, 0, 2.812]} scale={10.726} />
      </group>
    </group>
  )
}

useGLTF.preload(drone)
