/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/gasstruckonly.glb -o src/views/home/comModels/GasTruckOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import gastruck from '../../../assets/models/animatedModels/gasstruckonly.glb';
export function GasTruckOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(gastruck)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.gastruck) {
      actions.gastruck.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Gas_Truck001" castShadow receiveShadow geometry={nodes.Gas_Truck001.geometry} material={materials.Mat} position={[9.411, -0.277, 260.064]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={7.446} />
      </group>
    </group>
  )
}

useGLTF.preload(gastruck)
