/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/taxionly.glb -o src/views/home/comModels/TaxiOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import taxi from '../../../assets/models/animatedModels/taxionly.glb'
export function TaxiOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(taxi)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions.taxiii2) {
      actions.taxiii2.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Taxi002" castShadow receiveShadow geometry={nodes.Taxi002.geometry} material={materials.Mat} position={[879.073, -0.276, -33.309]} rotation={[Math.PI / 2, 0, -1.361]} scale={7.446} />
      </group>
    </group>
  )
}

useGLTF.preload(taxi)
