/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/truckonly.glb -o src/views/home/comModels/TruckOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import truck from '../../../assets/models/animatedModels/truckonly.glb';
export function TruckOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(truck)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.pickup4) {
      actions.pickup4.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Pickup_1003" castShadow receiveShadow geometry={nodes.Pickup_1003.geometry} material={materials.Mat} position={[671.278, -0.276, 277.275]} rotation={[Math.PI / 2, 0, 2.339]} scale={7.446} />
      </group>
    </group>
  )
}

useGLTF.preload(truck)
