/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 src/assets/models/animatedModels/truck2only.glb -o src/views/home/comModels/TruckTwoOnly.jsx -k -K -r -s public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import truckmodel from '../../../assets/models/animatedModels/truck2only.glb';
export function TruckTwoOnly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(truckmodel)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.maintruckk) {
      actions.maintruckk.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Main_Truck_1001" castShadow receiveShadow geometry={nodes.Main_Truck_1001.geometry} material={materials.Mat} position={[890.104, -0.277, -383.05]} rotation={[Math.PI / 2, 0, -1.78]} scale={7.446} />
      </group>
    </group>
  )
}

useGLTF.preload(truckmodel)
