import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Box3, Vector3 } from "three";
import model from "../../../../assets/models/aboutus/estore.glb";

export default function RetailModel(props) {
  const { nodes, materials } = useGLTF(model);
  const modelRef = useRef();

  useEffect(() => {
    if (modelRef.current) {
      const box = new Box3().setFromObject(modelRef.current);
      const center = new Vector3();
      box.getCenter(center);
      modelRef.current.position.sub(center); // Center the model
    }
  }, []);
  return (
    <group ref={modelRef}>
      <group {...props} dispose={null} scale={0.012}>
        <group rotation={[0, -0.02, Math.PI]} scale={[0.011, 0.01, 0.011]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110.geometry}
            material={materials["Material.8051"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_2.geometry}
            material={materials["Material.8057"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_3.geometry}
            material={materials["Material.7536"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_4.geometry}
            material={materials["Material.7537"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_5.geometry}
            material={materials["Material.3798"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_6.geometry}
            material={materials["Material.8056"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_7.geometry}
            material={materials["Material.8504"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_8.geometry}
            material={materials["Material.8054"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_9.geometry}
            material={materials["Material.8055"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_10.geometry}
            material={materials["Material.8052"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_11.geometry}
            material={materials["Material.8053"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_12.geometry}
            material={materials["Material.8505"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_13.geometry}
            material={materials["Material.6163"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_14.geometry}
            material={materials["Material.6164"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_15.geometry}
            material={materials["Material.6165"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_16.geometry}
            material={materials["Material.8503"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_17.geometry}
            material={materials["Material.8502"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_18.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_19.geometry}
            material={materials["Material.222"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_20.geometry}
            material={materials["Material.226"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_21.geometry}
            material={materials["Material.223"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_22.geometry}
            material={materials["Material.224"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_23.geometry}
            material={materials["Material.225"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_24.geometry}
            material={materials["Material.227"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_25.geometry}
            material={materials["Material.228"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_26.geometry}
            material={materials["Material.229"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_27.geometry}
            material={materials["Material.230"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_28.geometry}
            material={materials["Material.234"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_29.geometry}
            material={materials["Material.235"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_30.geometry}
            material={materials["Material.233"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_31.geometry}
            material={materials["Material.232"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_32.geometry}
            material={materials["Material.238"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_33.geometry}
            material={materials["Material.239"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_34.geometry}
            material={materials["Material.240"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_35.geometry}
            material={materials["Material.241"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_36.geometry}
            material={materials["Material.242"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_37.geometry}
            material={materials["Material.246"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_38.geometry}
            material={materials["Material.247"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_39.geometry}
            material={materials["Material.231"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_40.geometry}
            material={materials["Material.236"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_41.geometry}
            material={materials["Material.245"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Untitled110_42.geometry}
            material={materials["Material.248"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(model);
